# Generated by Django 5.2.16 on 2026-07-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_tlhti0.jpg', upload_to='profile_pics'),
        ),
    ]
