# Generated by Django 4.2.30 on 2026-06-11 19:42

from django.db import migrations
from django.utils.text import slugify


def generate_unique_slugs(apps, schema_editor):
    # Fetch the model from the migration state, NOT from your models.py
    Post = apps.get_model("blog", "Post")

    for post in Post.objects.all():
        # Generate a slug based on the title
        base_slug = slugify(post.title)
        post.slug = base_slug
        # (In a real app, you'd add logic here to handle duplicate titles)
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_slug"),
    ]

    operations = [
        migrations.RunPython(
            generate_unique_slugs, reverse_code=migrations.RunPython.noop
        ),
    ]
