# Generated by Django 4.2.30 on 2026-07-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_deletd',
            field=models.BooleanField(default=False),
        ),
    ]
