# Generated by Django 4.2.30 on 2026-07-02 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_is_deletd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_deletd',
            new_name='is_deleted',
        ),
    ]
